In [1]:
import numpy as np

### Task 1  
 Load an array from the file `data1.csv` into an ndarray object. Multiply all its elements by a specified value and save the result to the file `out1.csv`. Ensure the code is flexible and follows a proper application structure.



In [2]:
def multiply_and_save_matrix(input_file: str, output_file: str, multiplier: int) -> np.array:

    # Load data
    data_csv = np.loadtxt(input_file, delimiter=',')

    # Multiply array by constant
    data_output = data_csv * multiplier

    # Save result
    np.savetxt(output_file, data_output, delimiter=',')

    return data_output

result = multiply_and_save_matrix('data/data1.csv', 'data/out1.csv', 5)

print(result)

[[ 5.  5.  5.]
 [10. 10. 10.]
 [15. 15. 15.]
 [20. 20. 20.]
 [25. 25. 25.]
 [30. 30. 30.]]


### Task 2

Load a 2D array from the file `data1.csv` into an `ndarray` object. In the file `data2.csv`, the first row contains two natural numbers, and the second row contains another two natural numbers. These represent the ranges of rows (first row) and columns (second row). Extract the elements of the array based on the specified ranges and save the resulting new array to the file `out1.csv`.




In [3]:
def process_matrix(input_file: str, input_file_2: str, output_file: str) -> np.array:

    # Data loading
    data = np.loadtxt(input_file, delimiter=',')

    # Range data loading
    range_array = np.genfromtxt(input_file_2, delimiter=',', dtype=int)

    # Ranges
    row_start, row_end = range_array[0]
    col_start, col_end = range_array[1]

    # Define new matrix based on input with ranges
    data_to_save = data[row_start:row_end+1, col_start:col_end+1]

    # Data to save
    np.savetxt(output_file, data_to_save, delimiter=',')

    return data_to_save

result = process_matrix('data/data1.csv', 'data/data2.csv', 'data/out2.csv')

print(result)

[[1. 1.]
 [2. 2.]]


### TASK 3
Load two arrays of floating-point numbers from the files `data1.csv` and `data2.csv`. If the arrays have the same dimensions, allow the user to select the type of operation they want to perform on them (addition, subtraction, multiplication). Save the result of the operation to a file with a name specified by the user. Ensure the code is flexible and clear.



In [4]:
def process_files_and_perform_operation(input_file_1: str, input_file_2: str, output_file: str) -> np.array:
    try:
        # Data lading
        array1 = np.loadtxt(input_file_1, delimiter=',')
        array2 = np.loadtxt(input_file_2, delimiter=',')

        # Size check
        if array1.shape != array2.shape:
            print("Arrays should have the same shape.")
            return

        operation = input("Choose operation (add, subtract, multiply, divide: ").lower()

        # Choose operation
        match operation:
            case 'add':
                result = np.add(array1, array2)
            case 'subtract':
                result = np.subtract(array1, array2)
            case 'multiply':
                result = np.multiply(array1, array2)
            case 'divide':
                result = np.divide(array1, array2)
            case _:
                print("Operation unknown")
                return

        # Save result
        np.savetxt(output_file, result, delimiter=',')
        print(f"Result of'{operation}' saved to {output_file}")
    
    except Exception as e:
        print(f"Error: {e}")

    return result

# Main logic
file1 = 'data/data31.csv'
file2 = 'data/data32.csv'
output_file = 'data/out3.csv'

result = process_files_and_perform_operation(file1, file2, output_file)
print(result)

Result of'add' saved to data/out3.csv
[[ 3.1  4.2 11.3]
 [ 7.4  6.5  8.6]
 [ 9.2 15.8 19.9]]
