#### Task 1. Parallel Resistance Calculation

Calculate the equivalent resistance of resistors connected in parallel, using the formula:
$1/Rz = 1/R1 + 1/R2 + ... + 1/Rn$


In [1]:
import numpy as np

# Example array of resistor values
resistances = np.array([10, 20, 30])  # Resistance values in ohms

# Calculate the reciprocal of the equivalent resistance
reciprocal_rz = np.sum(1 / resistances)

# Calculate the equivalent resistance
rz = 1 / reciprocal_rz
print(f"Equivalent Resistance: {rz} ohms")

Equivalent Resistance: 5.454545454545454 ohms


#### Task 2
1. Take data about points and angles directly from arrays
2. Compute new points obtained by rotating the original points by each angle
3. For each rotation, calculate the total distance of all points from the origin.
4. Determine which rotated set of points has the largest total distance and save this set as the result.

In [3]:
my_points = np.array([[1,0], [0, 1], [1, 6]])
my_angles = np.array([10,20,60,90])

# Create rotation matrix, input in degrees
def create_rotation_matrix_2D(angle_degrees: float) -> np.ndarray:
  angle_radians = np.radians(angle_degrees)
  cos_angle = np.cos(angle_radians)
  sin_angle = np.sin(angle_radians)
  return np.array([
      [cos_angle, -sin_angle],
      [sin_angle, cos_angle]
  ])

# save rotated points, rounding to 0
def rotate_points_2D(points: np.array, angle_degrees: float) -> np.array:
  rotation_matrix = create_rotation_matrix_2D(angle_degrees)
  return np.round(np.dot(points, rotation_matrix.T), decimals=6)

# calculate distance from (0,0)
def total_distance_from_origin(points):
    return np.sum(np.linalg.norm(points, axis=1))

# Main function, finding the best rotation
def find_best_rotation(points, angles):
    max_distance = -np.inf
    best_rotation_points = None

    for angle in angles:
        print('rotated points:')
        rotated_points = rotate_points_2D(points, angle)
        print(rotated_points)
        print('distance from origin:')
        distance = total_distance_from_origin(rotated_points)
        print(distance)
        if distance > max_distance:
            max_distance = distance
            best_rotation_points = rotated_points

    return best_rotation_points


best_points = find_best_rotation(my_points, my_angles)

print("Best points:")
print(best_points)


rotated points
[[ 0.984808  0.173648]
 [-0.173648  0.984808]
 [-0.057081  6.082495]]
distance from origin
8.08276325637548
rotated points
[[ 0.939693  0.34202 ]
 [-0.34202   0.939693]
 [-1.112428  5.980176]]
distance from origin
8.082763230940948
rotated points
[[ 0.5       0.866025]
 [-0.866025  0.5     ]
 [-4.696152  3.866025]]
distance from origin
8.082761247941985
rotated points
[[ 0.  1.]
 [-1.  0.]
 [-6.  1.]]
distance from origin
8.082762530298218
Best points:
[[ 0.984808  0.173648]
 [-0.173648  0.984808]
 [-0.057081  6.082495]]
