#### 1. Task Description:

1. You have two arrays named `points1` and `points2`. Each array contains the same number of rows, and each row represents a point in 3D space. For example, the structure of an array could be:
   ```
   [[1, 2, 3],
    [4, 5, 6],
    [6, 7, 8]]
   ```

2. Compare the points located in the same row of both arrays. For each pair of points:
   - If the distance of the point from the first array to the origin `(0, 0, 0)` is greater than the distance of the corresponding point from the second array, write the coordinates of the point from the first array to the result.
   - Otherwise, write the coordinates of the point that is the farthest from the origin among the two into the result.


In [10]:
import numpy as np
points1 = np.array([[1,5,6],[4,5,6],[7,3,2]])
points2 = np.array([[3,2,4],[3,2,3],[6,4,5]])

def distance_from_origin_3d(points: np.ndarray) -> np.ndarray:
    return np.sqrt(np.sum(points**2, axis=1))

p1 = distance_from_origin_3d(points1)
p2 = distance_from_origin_3d(points2)

print('Dictances from the origin for set 1 of points:')
print(p1)
print('Dictances from the origin for set 2 of points:')
print(p2)

res = np.where(p1 > p2, p1, p2)
print('Result:')
print(res)

Dictances from the origin for set 1 of points:
[7.87400787 8.77496439 7.87400787]
Dictances from the origin for set 2 of points:
[5.38516481 4.69041576 8.77496439]
Result:
[7.87400787 8.77496439 8.77496439]


#### 2.Task Description:

1. You have two arrays named `points` and `circles`. The `points` array contains the coordinates of points in 2D space, where each row represents a point with `x` and `y` coordinates. For example:
   ```
   [[1, 2],
    [3, 4],
    [5, 6]]
   ```

   The `circles` array contains the coordinates of the circle centers and their radii. Each row represents a circle with `x`, `y`, and `radius`. For example:
   ```
   [[0, 0, 5],
    [2, 3, 10]]
   ```

2. For each point in the `points` array, determine if it lies inside any circle from the `circles` array. A point lies inside a circle if the distance from the point to the circle's center is less than or equal to the circle's radius.

3. Among the points that satisfy this condition, write to the result the point closest to the center of the circle in which it resides.



In [11]:
points = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

circles = np.array([[0, 0, 5],
                    [2, 3, 10]])

# Initialize result list to store the closest point for each circle
closest_points_dict = {}

# Iterate through each circle
for circle in circles:
    circle_x, circle_y, radius = circle

    # Compute distances of all points from the circle's center
    distances = np.sqrt((points[:, 0] - circle_x) ** 2 + (points[:, 1] - circle_y) ** 2)
    print('Distances from the circle center:')
    print(distances)
    print('Radius:')
    print(radius)
    inside_indices = np.where(distances <= radius)[0]
    print('Points inside the circle:')
    print(inside_indices)
    # Filter points that lie inside the circle
    if len(inside_indices) > 0:
        min_value = np.min(distances[inside_indices])
        closest_indices = inside_indices[np.where(distances[inside_indices] == min_value)]
        print(closest_indices)

        # Add the closest point to the result
        closest_points_dict[(circle_x, circle_y, radius)] = points[closest_indices]

for circle, closest_pts in closest_points_dict.items():
    print(f"Koło (x={circle[0]}, y={circle[1]}, r={circle[2]}): {closest_pts}")

Distances from the circle center:
[2.23606798 5.         7.81024968]
Radius:
5
Points inside the circle:
[0 1]
[0]
Distances from the circle center:
[1.41421356 1.41421356 4.24264069]
Radius:
10
Points inside the circle:
[0 1 2]
[0 1]
Koło (x=0, y=0, r=5): [[1 2]]
Koło (x=2, y=3, r=10): [[1 2]
 [3 4]]
